version: '2.4'

services:
    service_1:
      container_name: service_1
      image: leoverto/dummy-image
      networks:
        - network_a
        - network_b
    service_2:
      container_name: service_2
      image: leoverto/dummy-image
      networks:
        network_b:
        network_c:
          aliases:
            - "s2.netc"
    service_3:
      container_name: service_3
      image: leoverto/dummy-image
      networks:
        - network_a
        - network_b
        - network_c
        - no_gateway
    service_4:
      container_name: service_4
      image: leoverto/dummy-image
      ports:
        - "1234:1234"
        - "0.0.0.0:5678:5678/udp"
      networks:
        - internet
    host_service:
      container_name: host_service
      image: leoverto/dummy-image
      network_mode: host
    isolated_service:
      container_name: isolated_service
      image: leoverto/dummy-image
      network_mode: none

networks:
  internet: 
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
  network_a:
  network_b:
  network_c:
  empty_network:
  no_gateway:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-no-gateway
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
